/*******************************************************************************
* FILENAME: project.h
* 
* PSoC Creator  3.2
*
* DESCRIPTION:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Servo_B.h"
#include "Servo_1B_aliases.h"
#include "Servo_1B.h"
#include "Servo_2B_aliases.h"
#include "Servo_2B.h"
#include "Servo_1A_aliases.h"
#include "Servo_1A.h"
#include "Servo_2A_aliases.h"
#include "Servo_2A.h"
#include "Servo_A.h"
#include "Clock_1.h"
#include "EN_A_PWM.h"
#include "IN_3_aliases.h"
#include "IN_3.h"
#include "EN_B_PWM.h"
#include "EN_A_aliases.h"
#include "EN_A.h"
#include "EN_B_aliases.h"
#include "EN_B.h"
#include "Motor_A.h"
#include "Motor_B.h"
#include "IN_4_aliases.h"
#include "IN_4.h"
#include "IN_1_aliases.h"
#include "IN_1.h"
#include "IN_2_aliases.h"
#include "IN_2.h"
#include "Clock_2.h"
#include "SDA_1_aliases.h"
#include "SDA_1.h"
#include "SCL_1_aliases.h"
#include "SCL_1.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "UART.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

